export const SUBSCRIPTION_TIERS = {
  STARTER: {
    name: 'Starter',
    description: 'Perfect for small teams and startups',
    priceMonthly: 29,
    priceYearly: 290,
    features: [
      'Up to 5 users',
      'Real-time monitoring',
      'Basic analytics',
      'Email support',
      '7-day log retention',
      'API access (1,000 requests/day)',
    ],
  },
  PRO: {
    name: 'Professional',
    description: 'For growing teams and enterprises',
    priceMonthly: 99,
    priceYearly: 990,
    features: [
      'Up to 50 users',
      'Real-time monitoring',
      'Advanced analytics',
      'Priority support',
      '30-day log retention',
      'API access (50,000 requests/day)',
      'Custom dashboards',
      'Automated reports',
    ],
  },
  ENTERPRISE: {
    name: 'Enterprise',
    description: 'For large-scale operations',
    priceMonthly: 499,
    priceYearly: 4990,
    features: [
      'Unlimited users',
      'Real-time monitoring',
      'Advanced analytics',
      '24/7 dedicated support',
      '90-day log retention',
      'Unlimited API access',
      'Custom dashboards',
      'White-label options',
      'SLA guarantee (99.9%)',
    ],
  },
};
